version: '3.8'
name: task-manager

services:
  postgres:
    image: postgres:16
    container_name: task-manager-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - task-manager

  app:
    container_name: task-manager-app
    restart: unless-stopped
    build:
      context: php
    volumes:
      - ./app:/var/www/app
    depends_on:
      - postgres
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      PHP_IDE_CONFIG: 'serverName=App'
    networks:
      - task-manager

  nginx:
    container_name: task-manager-nginx
    restart: unless-stopped
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - postgres
    networks:
      - task-manager

volumes:
  postgres:

networks:
  task-manager:
    driver: bridge
